// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waldurhcavotghlinkbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhbGR1cmhjYXZvdGdobGlua2J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDI5NzMsImV4cCI6MjA1OTY3ODk3M30.wwmYwYNoXWWl8E4C0kMOWdrtwgPs21cBcA2KUUnS6ZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);